<?php

/**
 * @file
 * Contains ldbase_content.module.
 */

/**
 * Implements hook_node_view().
 */
function ldbase_content_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  $hierarchichal_ctypes = array('project', 'dataset', 'code', 'document', 'codebook');
  $ldbase_ctypes = array('project', 'dataset', 'code', 'document', 'person', 'organization', 'codebook');
  $ctype = \Drupal::service('ldbase.object_service')->isLdbaseCodebook($entity->uuid()) ? 'codebook' : $entity->bundle();
  if (in_array($ctype, $hierarchichal_ctypes)) {
    $build['#attached']['library'][] = 'ldbase_content/breadcrumb-current-page-prefixer';
  }
  if (in_array($ctype, $ldbase_ctypes)) {
    $title = $build['title'][0]['#context']['value'];
    $prefixed_title = t('@ctype: @title', ['@ctype' => ucfirst($ctype), '@title' => $title]);
    $build['title'][0]['#context']['value'] = $prefixed_title;
  }
  if ($ctype = 'dataset') {
    $file = [];
    if (!empty($entity->field_dataset_version)) {
      foreach ($entity->field_dataset_version as $delta => $file_metadata_paragraph) {
        $p = $file_metadata_paragraph->entity;
        $file[$delta]['dataset_version_id'] = $p->field_file_version_id->value;
      }
    }
    if (!empty($file)) {
      $latest_version = array_pop($file);
      $version_suffix = ' [v.' . $latest_version['dataset_version_id'] . ']';
      $build['title'][0]['#context']['value'] .= $version_suffix;
    }

  }
}

/**
 * Implements hook_form_alter().
 */
function ldbase_content_form_alter(&$form, Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    // change username label to Email Address
    $form['name']['#title'] = t('Email Address');
    $form['name']['#description'] = t('Enter your LDbase account email address.');

    $form['pass']['#description'] = t('Enter the password that accompanies your LDbase account.');

  }

  if ($form_id == 'user_pass') {
    $form['name']['#title'] = t('Email Address');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param $variables
 */
function ldbase_content_preprocess_status_messages(&$variables) {
  // modify error message for login from home and user.login
  $change_login_error_messages = ['ldbase.home','user.login'];
  $current_route = \Drupal::routeMatch()->getRouteName();
  if (in_array($current_route, $change_login_error_messages)) {
    if(isset($variables['message_list']['error'])){
      $status_messages = $variables['message_list']['error'];
      foreach($status_messages as $delta => $message) {
        if (strpos((string) $message, '1 error has been found') !== FALSE) {
          $variables['message_list']['error'][$delta] = "Unrecognized username or password.";
        }
      }
    }
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function ldbase_content_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
  if ($route_match && $node = $route_match->getParameter('node')) {
    $breadcrumb->addCacheableDependency($node);
  }
}

/**
 * Implements hook_theme().
 */
function ldbase_content_theme($existing, $type, $theme, $path) {
  return [
    'ldbase_content_browse_vocabularies' => [
      'template' => 'ldbase-content-browse-vocabularies',
      'variables' => [
        'count' => NULL,
        'vocabulary_links' => [],
      ],
    ],
    'ldbase_content_home_page_user_block' => [
      'template' => 'ldbase-content-home-page-user-block',
      'variables' => [
        'person_name' => NULL,
        'person_orcid' => NULL,
        'person_email' => NULL,
        'person_related_organizations' => NULL,
        'person_professional_titles' => [],
        'dashboard_link' => NULL,
        'messages_link' => NULL,
        'favorites_link' => NULL,
        'contributions_link' => NULL,
        'profile_edit_link' => NULL,
        'taxonomy_review_link' => NULL,
        'email_needs_verification' => NULL,
        'verification_link' => NULL,
      ],
    ],
    'ldbase_d3_contributions_block' => [
      'template' => 'ldbase-d3-visualization-block',
      'variables' => [
        'description' => NULL,
      ],
    ],
    'ldbase_d3_content_count_block' => [
      'template' => 'ldbase-d3-visualization-block',
      'variables' => [
        'description' => NULL,
      ],
    ],
    'ldbase_project_subtree' => [
      'template' => 'ldbase-project-subtree',
      'variables' => [
        'subtree_title' => NULL,
        'items' => NULL,
      ],
    ],
    'ldbase_latest_project_items' => [
      'template' => 'ldbase-latest-project-items',
      'variables' => [
        'section_prefix' => NULL,
        'section_suffix' => NULL,
        'block_data' => [],
      ]
    ]
  ];
}
