<?php

/**
 * @file
 * Contains ldbase_content.module.
 */

/**
 * Implements hook_node_view().
 */
function ldbase_content_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  $hierarchichal_ctypes = array('project', 'dataset', 'code', 'document', 'codebook');
  $ldbase_ctypes = array('project', 'dataset', 'code', 'document', 'person', 'organization', 'codebook');
  $ctype = \Drupal::service('ldbase.object_service')->isLdbaseCodebook($entity->uuid()) ? 'codebook' : $entity->bundle();
  if (in_array($ctype, $hierarchichal_ctypes)) {
    $build['#attached']['library'][] = 'ldbase_content/breadcrumb-current-page-prefixer';
  }
  if (in_array($ctype, $ldbase_ctypes)) {
    $title = $build['title'][0]['#context']['value'];
    $prefixed_title = t('@ctype: @title', ['@ctype' => ucfirst($ctype), '@title' => $title]);
    $build['title'][0]['#context']['value'] = $prefixed_title;
  }
}

/**
 * Implements hook_form_alter().
 */
function ldbase_content_form_alter(&$form, Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    // change username label to Email Address
    $form['name']['#title'] = t('Email Address');
    $form['name']['#description'] = t('Enter your LDbase account email address.');

    $form['pass']['#description'] = t('Enter the password that accompanies your LDbase account.');

  }

  if ($form_id == 'user_pass') {
    $form['name']['#title'] = t('Email Address');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param $variables
 */
function ldbase_content_preprocess_status_messages(&$variables) {
  // modify error message for login from home and user.login
  $change_login_error_messages = ['ldbase.home','user.login'];
  $current_route = \Drupal::routeMatch()->getRouteName();
  if (in_array($current_route, $change_login_error_messages)) {
    if(isset($variables['message_list']['error'])){
      $status_messages = $variables['message_list']['error'];
      foreach($status_messages as $delta => $message) {
        if (strpos((string) $message, '1 error has been found') !== FALSE) {
          $variables['message_list']['error'][$delta] = "Unrecognized username or password.";
        }
      }
    }
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function ldbase_content_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
  if ($route_match && $node = $route_match->getParameter('node')) {
    $breadcrumb->addCacheableDependency($node);
  }
}
